---
kind: pipeline
type: docker
name: BUILD-TEST
steps:
  - name: Build DEBIAN Buster
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      dockerfile: debian/debian-buster
      platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8
      repo: alcapone1933/debian
      tags: buster
      dry_run: true
  - name: Build DEBIAN Bullseye
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      dockerfile: debian/debian-bullseye
      platforms: linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/mips64le,linux/ppc64le,linux/s390x
      repo: alcapone1933/debian
      tags: bullseye
      dry_run: true
  - name: Build DEBIAN LATEST
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      dockerfile: debian/debian-latest
      platforms: linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/mips64le,linux/ppc64le,linux/s390x
      repo: alcapone1933/debian
      tags: latest
      dry_run: true
  - name: Build UBUNTU 20.04
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      dockerfile: ubuntu/ubuntu-20-04
      platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/riscv64,linux/s390x
      repo: alcapone1933/ubuntu
      tags: 20.04
      dry_run: true
  - name: Build UBUNTU 22.04
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      dockerfile: ubuntu/ubuntu-22-04
      platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/riscv64,linux/s390x
      repo: alcapone1933/ubuntu
      tags: 22.04
      dry_run: true
  - name: Build UBUNTU LATEST
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      dockerfile: ubuntu/ubuntu-latest
      platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/riscv64,linux/s390x
      repo: alcapone1933/ubuntu
      tags: latest
      dry_run: true	  

trigger:
  branch:
  - master
  event:
  # - push
  # - pull_request
  # - cron
  - custom
  # cron:
  # - weekly
---
kind: pipeline
type: docker
name: BUILD

steps:
  - name: Build DEBIAN Buster
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      username: 
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
      dockerfile: debian/debian-buster
      platforms: linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8
      repo: alcapone1933/debian
      tags: buster
  - name: Build DEBIAN Bullseye
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      username: 
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
      dockerfile: debian/debian-bullseye
      platforms: linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/mips64le,linux/ppc64le,linux/s390x
      repo: alcapone1933/debian
      tags: bullseye
  - name: Build DEBIAN LATEST
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      username: 
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
      dockerfile: debian/debian-latest
      platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/mips64le,linux/ppc64le,linux/s390x
      repo: alcapone1933/debian
      tags: latest
  - name: Build UBUNTU 20.04
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      username: 
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
      dockerfile: ubuntu/ubuntu-20-04
      platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/riscv64,linux/s390x
      repo: alcapone1933/ubuntu
      tags: 20.04
  - name: Build UBUNTU 22.04
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      username: 
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
      dockerfile: ubuntu/ubuntu-22-04
      platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/riscv64,linux/s390x
      repo: alcapone1933/ubuntu
      tags: 22.04
  - name: Build UBUNTU LATEST
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      username: 
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
      dockerfile: ubuntu/ubuntu-latest
      platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/riscv64,linux/s390x
      repo: alcapone1933/ubuntu
      tags: latest

trigger:
  branch:
  - master
  event:
  # - push
  # - pull_request
  # - cron
  - custom
  # cron:
  # - weekly

depends_on:
  - BUILD-TEST