---
kind: pipeline
type: docker
name: BUILD-TEST

steps:
  - name: Build_DEBIAN_Bookworm
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      dockerfile: debian/debian-bookworm
      platforms: linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/mips64le,linux/ppc64le,linux/s390x
      repo: alcapone1933/debian
      tags: bookworm
      dry_run: true
  - name: Build_DEBIAN_LATEST
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      dockerfile: debian/debian-latest
      platforms: linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/mips64le,linux/ppc64le,linux/s390x
      repo: alcapone1933/debian
      tags: latest
      dry_run: true
  - name: Build_UBUNTU_20.04
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      dockerfile: ubuntu/ubuntu-20-04
      platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/riscv64,linux/s390x
      repo: alcapone1933/ubuntu
      tags: 20.04
      dry_run: true
  - name: Build_UBUNTU_22.04
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      dockerfile: ubuntu/ubuntu-22-04
      platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/riscv64,linux/s390x
      repo: alcapone1933/ubuntu
      tags: 22.04
      dry_run: true
  - name: Build_UBUNTU_24.04
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      dockerfile: ubuntu/ubuntu-24-04
      platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/riscv64,linux/s390x
      repo: alcapone1933/ubuntu
      tags: 24.04
      dry_run: true
  - name: Build_UBUNTU_LATEST
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      dockerfile: ubuntu/ubuntu-latest
      platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/riscv64,linux/s390x
      repo: alcapone1933/ubuntu
      tags: latest
      dry_run: true
  - name: Build_ALPINE_LATEST
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      dockerfile: alpine/alpine-latest
      platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
      repo: alcapone1933/alpine
      tags: 
        - latest
        - v3.22
      dry_run: true
  - name: Build_ALPINE_TOOLS
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      dockerfile: alpine/alpine-tools
      platforms: linux/amd64,linux/arm64/v8
      repo: alcapone1933/alpine
      tags: tools
      dry_run: true

trigger:
  branch:
  - master
  event:
  # - push
  # - pull_request
  # - cron
  - custom
  # cron:
  # - weekly
---
kind: pipeline
type: docker
name: BUILD

steps:
  - name: Build_DEBIAN_Bookworm
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      username: 
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
      dockerfile: debian/debian-bookworm
      platforms: linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/mips64le,linux/ppc64le,linux/s390x
      repo: alcapone1933/debian
      tags: bookworm
  - name: Build_DEBIAN_LATEST
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      username: 
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
      dockerfile: debian/debian-latest
      platforms: linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/mips64le,linux/ppc64le,linux/s390x
      repo: alcapone1933/debian
      tags: latest
  - name: Build_UBUNTU_20.04
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      username: 
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
      dockerfile: ubuntu/ubuntu-20-04
      platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/riscv64,linux/s390x
      repo: alcapone1933/ubuntu
      tags: 20.04
  - name: Build_UBUNTU_22.04
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      username: 
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
      dockerfile: ubuntu/ubuntu-22-04
      platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/riscv64,linux/s390x
      repo: alcapone1933/ubuntu
      tags: 22.04
  - name: Build_UBUNTU_24.04
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      username: 
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
      dockerfile: ubuntu/ubuntu-24-04
      platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/riscv64,linux/s390x
      repo: alcapone1933/ubuntu
      tags: 24.04
  - name: Build_UBUNTU_LATEST
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      username: 
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
      dockerfile: ubuntu/ubuntu-latest
      platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/riscv64,linux/s390x
      repo: alcapone1933/ubuntu
      tags: latest
  - name: Build_ALPINE_LATEST
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      username: 
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
      dockerfile: alpine/alpine-latest
      platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
      repo: alcapone1933/alpine
      tags:
        - latest
        - v3.22
  - name: Build_ALPINE_TOOLS
    image: alcapone1933/drone:docker-buildx
    privileged: true
    settings:
      username: 
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
      dockerfile: alpine/alpine-tools
      platforms: linux/amd64,linux/arm64/v8
      repo: alcapone1933/alpine
      tags: tools

trigger:
  branch:
  - master
  event:
  # - push
  # - pull_request
  # - cron
  - custom
  # cron:
  # - weekly

depends_on:
  - BUILD-TEST
