---
kind: pipeline
type: docker
name: BUILD-TEST

steps:
  - name: Build Multi-arch TEST DEBIAN Buster
    image: alcapone1933/docker-dind:latest
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PASS:
        from_secret: DOCKER_PASS
    commands:
      - sleep 10
      - echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - docker buildx create --name debian-buster --platform linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8 --driver-opt network=host,image=alcapone1933/buildkit:latest --bootstrap --use
      - docker buildx ls
      - docker buildx inspect debian-buster
      - docker buildx build --progress=plain --platform linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8 -t alcapone1933/debian:buster -f debian/debian-buster .
      - docker buildx rm debian-buster
      - docker buildx ls
  - name: Build Multi-arch TEST DEBIAN Bullseye
    image: alcapone1933/docker-dind:latest
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PASS:
        from_secret: DOCKER_PASS
    commands:
      - sleep 5
      - echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - docker buildx create --name debian-bullseye --platform linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/mips64le,linux/ppc64le,linux/s390x --driver-opt network=host,image=alcapone1933/buildkit:latest --bootstrap --use
      - docker buildx ls
      - docker buildx inspect debian-bullseye
      - docker buildx build --progress=plain --platform linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/mips64le,linux/ppc64le,linux/s390x -t alcapone1933/debian:bullseye -f debian/debian-bullseye .
      - docker buildx rm debian-bullseye
      - docker buildx ls
  - name: Build Multi-arch TEST DEBIAN LATEST
    image: alcapone1933/docker-dind:latest
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PASS:
        from_secret: DOCKER_PASS
    commands:
      - sleep 5
      - echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - docker buildx create --name debian-latest --platform linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/mips64le,linux/ppc64le,linux/s390x --driver-opt network=host,image=alcapone1933/buildkit:latest --bootstrap --use
      - docker buildx ls
      - docker buildx inspect debian-latest
      - docker buildx build --progress=plain --platform linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/mips64le,linux/ppc64le,linux/s390x -t alcapone1933/debian:latest -f debian/debian-latest .
      - docker buildx rm debian-latest
      - docker buildx ls
  - name: Build Multi-arch TEST UBUNTU 20.04
    image: alcapone1933/docker-dind:latest
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PASS:
        from_secret: DOCKER_PASS
    commands:
      - sleep 5
      - echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - docker buildx create --name ubuntu-20-04 --platform linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x --driver-opt network=host,image=alcapone1933/buildkit:latest --bootstrap --use
      - docker buildx ls
      - docker buildx inspect ubuntu-20-04
      - docker buildx build --progress=plain --platform linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x -t alcapone1933/ubuntu:20.04 -f ubuntu/ubuntu-20-04 .
      - docker buildx rm ubuntu-20-04
      - docker buildx ls
  - name: Build Multi-arch TEST UBUNTU 22.04
    image: alcapone1933/docker-dind:latest
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PASS:
        from_secret: DOCKER_PASS
    commands:
      - sleep 5
      - echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - docker buildx create --name ubuntu-22-04 --platform linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x --driver-opt network=host,image=alcapone1933/buildkit:latest --bootstrap --use
      - docker buildx ls
      - docker buildx inspect ubuntu-22-04
      - docker buildx build --progress=plain --platform linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x -t alcapone1933/ubuntu:22.04 -f ubuntu/ubuntu-22-04 .
      - docker buildx rm ubuntu-22-04
      - docker buildx ls
  - name: Build Multi-arch TEST UBUNTU LATEST
    image: alcapone1933/docker-dind:latest
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PASS:
        from_secret: DOCKER_PASS
    commands:
      - sleep 5
      - echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - docker buildx create --name ubuntu-latest --platform linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x --driver-opt network=host,image=alcapone1933/buildkit:latest --bootstrap --use
      - docker buildx ls
      - docker buildx inspect ubuntu-latest
      - docker buildx build --progress=plain --platform linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x -t alcapone1933/ubuntu:latest -f ubuntu/ubuntu-latest .
      - docker buildx rm ubuntu-latest
      - docker buildx ls
  - name: Build Multi-arch TEST ALPINE LATEST
    image: alcapone1933/docker-dind:latest
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PASS:
        from_secret: DOCKER_PASS
    commands:
      - sleep 5
      - echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - docker buildx create --name alpine-latest --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x --driver-opt network=host,image=alcapone1933/buildkit:latest --bootstrap --use
      - docker buildx ls
      - docker buildx inspect alpine-latest
      - docker buildx build --progress=plain --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x -t alcapone1933/alpine:latest -f alpine/alpine-latest .
      - docker buildx rm alpine-latest
      - docker buildx ls
  - name: Build Multi-arch TEST ALPINE TOOLS
    image: alcapone1933/docker-dind:latest
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PASS:
        from_secret: DOCKER_PASS
    commands:
      - sleep 5
      - echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - docker buildx create --name alpine-tools --platform linux/amd64,linux/arm/v7,linux/arm64/v8 --driver-opt network=host,image=alcapone1933/buildkit:latest --bootstrap --use
      - docker buildx ls
      - docker buildx inspect alpine-tools
      - docker buildx build --progress=plain --platform linux/amd64,linux/arm/v7,linux/arm64/v8 -t alcapone1933/alpine:tools -f alpine/alpine-tools .
      - docker buildx rm alpine-tools
      - docker buildx ls

services:
  - name: docker
    image: alcapone1933/docker-dind:latest
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

trigger:
  branch:
  - master
  event:
  # - push
  # - pull_request
  - custom

---
kind: pipeline
type: docker
name: BUILD-Dockerhub

steps:
  - name: Build Multi-arch DEBIAN Buster
    image: alcapone1933/docker-dind:latest
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PASS:
        from_secret: DOCKER_PASS
    commands:
      - sleep 10
      - echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - docker buildx create --name debian-buster --platform linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8 --driver-opt network=host,image=alcapone1933/buildkit:latest --bootstrap --use
      - docker buildx ls
      - docker buildx inspect debian-buster
      - docker buildx build --progress=plain --platform linux/386,linux/amd64,linux/arm/v7,linux/arm64/v8 -t alcapone1933/debian:buster -f debian/debian-buster --push .
      - docker buildx rm debian-buster
      - docker buildx ls
  - name: Build Multi-arch DEBIAN Bullseye
    image: alcapone1933/docker-dind:latest
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PASS:
        from_secret: DOCKER_PASS
    commands:
      - sleep 5
      - echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - docker buildx create --name debian-bullseye --platform linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/mips64le,linux/ppc64le,linux/s390x --driver-opt network=host,image=alcapone1933/buildkit:latest --bootstrap --use
      - docker buildx ls
      - docker buildx inspect debian-bullseye
      - docker buildx build --progress=plain --platform linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/mips64le,linux/ppc64le,linux/s390x -t alcapone1933/debian:bullseye -f debian/debian-bullseye --push .
      - docker buildx rm debian-bullseye
      - docker buildx ls
  - name: Build Multi-arch DEBIAN LATEST
    image: alcapone1933/docker-dind:latest
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PASS:
        from_secret: DOCKER_PASS
    commands:
      - sleep 5
      - echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - docker buildx create --name debian-latest --platform linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/mips64le,linux/ppc64le,linux/s390x --driver-opt network=host,image=alcapone1933/buildkit:latest --bootstrap --use
      - docker buildx ls
      - docker buildx inspect debian-latest
      - docker buildx build --progress=plain --platform linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/mips64le,linux/ppc64le,linux/s390x -t alcapone1933/debian:latest -f debian/debian-latest --push .
      - docker buildx rm debian-latest
      - docker buildx ls
  - name: Build Multi-arch UBUNTU 20.04
    image: alcapone1933/docker-dind:latest
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PASS:
        from_secret: DOCKER_PASS
    commands:
      - sleep 5
      - echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - docker buildx create --name ubuntu-20-04 --platform linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x --driver-opt network=host,image=alcapone1933/buildkit:latest --bootstrap --use
      - docker buildx ls
      - docker buildx inspect ubuntu-20-04
      - docker buildx build --progress=plain --platform linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x -t alcapone1933/ubuntu:20.04 -f ubuntu/ubuntu-20-04 --push .
      - docker buildx rm ubuntu-20-04
      - docker buildx ls
  - name: Build Multi-arch UBUNTU 22.04
    image: alcapone1933/docker-dind:latest
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PASS:
        from_secret: DOCKER_PASS
    commands:
      - sleep 5
      - echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - docker buildx create --name ubuntu-22-04 --platform linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x --driver-opt network=host,image=alcapone1933/buildkit:latest --bootstrap --use
      - docker buildx ls
      - docker buildx inspect ubuntu-22-04
      - docker buildx build --progress=plain --platform linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x -t alcapone1933/ubuntu:22.04 -f ubuntu/ubuntu-22-04 --push .
      - docker buildx rm ubuntu-22-04
      - docker buildx ls
  - name: Build Multi-arch UBUNTU LATEST
    image: alcapone1933/docker-dind:latest
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PASS:
        from_secret: DOCKER_PASS
    commands:
      - sleep 5
      - echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - docker buildx create --name ubuntu-latest --platform linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x --driver-opt network=host,image=alcapone1933/buildkit:latest --bootstrap --use
      - docker buildx ls
      - docker buildx inspect ubuntu-latest
      - docker buildx build --progress=plain --platform linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x -t alcapone1933/ubuntu:latest -f ubuntu/ubuntu-latest --push .
      - docker buildx rm ubuntu-latest
      - docker buildx ls
  - name: Build Multi-arch ALPINE VERSION
    image: alcapone1933/docker-dind:latest
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PASS:
        from_secret: DOCKER_PASS
    commands:
      - sleep 5
      - echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - docker buildx create --name alpine-v3.18 --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x --driver-opt network=host,image=alcapone1933/buildkit:latest --bootstrap --use
      - docker buildx ls
      - docker buildx inspect alpine-v3.18
      - docker buildx build --progress=plain --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x -t alcapone1933/alpine:v3.18 -f alpine/alpine-latest --push .
      - docker buildx rm alpine-v3.18
      - docker buildx ls
  - name: Build Multi-arch ALPINE LATEST
    image: alcapone1933/docker-dind:latest
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PASS:
        from_secret: DOCKER_PASS
    commands:
      - sleep 5
      - echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - docker buildx create --name alpine-latest --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x --driver-opt network=host,image=alcapone1933/buildkit:latest --bootstrap --use
      - docker buildx ls
      - docker buildx inspect alpine-latest
      - docker buildx build --progress=plain --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x -t alcapone1933/alpine:latest -f alpine/alpine-latest --push .
      - docker buildx rm alpine-latest
      - docker buildx ls
  - name: Build Multi-arch ALPINE TOOLS
    image: alcapone1933/docker-dind:latest
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_USER:
        from_secret: DOCKER_USER
      DOCKER_PASS:
        from_secret: DOCKER_PASS
    commands:
      - sleep 5
      - echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
      - docker buildx create --name alpine-tools --platform linux/amd64,linux/arm/v7,linux/arm64/v8 --driver-opt network=host,image=alcapone1933/buildkit:latest --bootstrap --use
      - docker buildx ls
      - docker buildx inspect alpine-tools
      - docker buildx build --progress=plain --platform linux/amd64,linux/arm/v7,linux/arm64/v8 -t alcapone1933/alpine:tools -f alpine/alpine-tools --push .
      - docker buildx rm alpine-tools
      - docker buildx ls

services:
  - name: docker
    image: alcapone1933/docker-dind:latest
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

trigger:
  branch:
  - master
  event:
  # - push
  # - pull_request
  - custom

depends_on:
  - BUILD-TEST